/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Blog = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorId' : IDL.Text,
  'createdAt' : IDL.Int,
  'blogType' : IDL.Text,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
});
export const AppointmentSummary = IDL.Record({
  'total' : IDL.Nat,
  'cancelled' : IDL.Nat,
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'approved' : IDL.Nat,
});
export const TrendEntry = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'doctorId' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'slot' : IDL.Text,
  'updatedAt' : IDL.Int,
  'notes' : IDL.Text,
  'patientName' : IDL.Text,
  'phone' : IDL.Text,
  'problem' : IDL.Text,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'doctor' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const AppointmentStats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
  'rejected' : IDL.Nat,
  'accepted' : IDL.Nat,
});
export const AvailabilitySlot = IDL.Record({
  'endHour' : IDL.Nat,
  'dayOfWeek' : IDL.Text,
  'startHour' : IDL.Nat,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'appointmentStats' : AppointmentStats,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'availability' : IDL.Vec(AvailabilitySlot),
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
  'lastLogin' : IDL.Int,
});
export const DoctorPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'availability' : IDL.Vec(AvailabilitySlot),
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'appointmentIds' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mapUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const FAQ = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'order' : IDL.Nat,
  'answer' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'text' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ServiceCard = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const SiteContent = IDL.Record({
  'contactInfo' : ContactInfo,
  'faqs' : IDL.Vec(FAQ),
  'heroCtaText' : IDL.Text,
  'heroIntro' : IDL.Text,
  'testimonials' : IDL.Vec(Testimonial),
  'heroTitle' : IDL.Text,
  'services' : IDL.Vec(ServiceCard),
  'heroTagline' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addDoctor' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [Result_1],
      [],
    ),
  'createBlog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [Result], []),
  'deleteBlog' : IDL.Func([IDL.Nat], [Result], []),
  'editBlog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'editDoctor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'getAppointmentStats' : IDL.Func([], [AppointmentSummary], ['query']),
  'getAppointmentTrend' : IDL.Func([IDL.Nat], [IDL.Vec(TrendEntry)], ['query']),
  'getAppointments' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByDoctor' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getAuditLogsByUser' : IDL.Func([IDL.Text], [IDL.Vec(AuditLog)], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDoctorById' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
  'getDoctorStats' : IDL.Func([IDL.Nat], [AppointmentStats], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(DoctorPublic)], ['query']),
  'getPatientByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
  'getPatientHistory' : IDL.Func([IDL.Nat], [IDL.Vec(Appointment)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPublishedBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishBlog' : IDL.Func([IDL.Nat], [Result], []),
  'registerUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, UserRole],
      [Result],
      [],
    ),
  'rescheduleAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [Result],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'setDoctorAvailability' : IDL.Func(
      [IDL.Nat, IDL.Vec(AvailabilitySlot)],
      [Result],
      [],
    ),
  'toggleDoctorOnlineStatus' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'unpublishBlog' : IDL.Func([IDL.Nat], [Result], []),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateFAQs' : IDL.Func([IDL.Vec(FAQ)], [Result], []),
  'updateHeroSection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'updateServices' : IDL.Func([IDL.Vec(ServiceCard)], [Result], []),
  'updateTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [Result], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Blog = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorId' : IDL.Text,
    'createdAt' : IDL.Int,
    'blogType' : IDL.Text,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
  });
  const AppointmentSummary = IDL.Record({
    'total' : IDL.Nat,
    'cancelled' : IDL.Nat,
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'approved' : IDL.Nat,
  });
  const TrendEntry = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'doctorId' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'slot' : IDL.Text,
    'updatedAt' : IDL.Int,
    'notes' : IDL.Text,
    'patientName' : IDL.Text,
    'phone' : IDL.Text,
    'problem' : IDL.Text,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'doctor' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const AppointmentStats = IDL.Record({
    'total' : IDL.Nat,
    'completed' : IDL.Nat,
    'rejected' : IDL.Nat,
    'accepted' : IDL.Nat,
  });
  const AvailabilitySlot = IDL.Record({
    'endHour' : IDL.Nat,
    'dayOfWeek' : IDL.Text,
    'startHour' : IDL.Nat,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'appointmentStats' : AppointmentStats,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'availability' : IDL.Vec(AvailabilitySlot),
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
    'lastLogin' : IDL.Int,
  });
  const DoctorPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'availability' : IDL.Vec(AvailabilitySlot),
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'appointmentIds' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mapUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const FAQ = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'order' : IDL.Nat,
    'answer' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'text' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ServiceCard = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const SiteContent = IDL.Record({
    'contactInfo' : ContactInfo,
    'faqs' : IDL.Vec(FAQ),
    'heroCtaText' : IDL.Text,
    'heroIntro' : IDL.Text,
    'testimonials' : IDL.Vec(Testimonial),
    'heroTitle' : IDL.Text,
    'services' : IDL.Vec(ServiceCard),
    'heroTagline' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addDoctor' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [Result_1],
        [],
      ),
    'createBlog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [Result], []),
    'deleteBlog' : IDL.Func([IDL.Nat], [Result], []),
    'editBlog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'editDoctor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'getAllBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'getAppointmentStats' : IDL.Func([], [AppointmentSummary], ['query']),
    'getAppointmentTrend' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TrendEntry)],
        ['query'],
      ),
    'getAppointments' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByDoctor' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getAuditLogsByUser' : IDL.Func([IDL.Text], [IDL.Vec(AuditLog)], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDoctorById' : IDL.Func([IDL.Nat], [IDL.Opt(Doctor)], ['query']),
    'getDoctorStats' : IDL.Func([IDL.Nat], [AppointmentStats], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(DoctorPublic)], ['query']),
    'getPatientByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Patient)], ['query']),
    'getPatientHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPublishedBlogs' : IDL.Func([], [IDL.Vec(Blog)], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishBlog' : IDL.Func([IDL.Nat], [Result], []),
    'registerUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, UserRole],
        [Result],
        [],
      ),
    'rescheduleAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [Result],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'setDoctorAvailability' : IDL.Func(
        [IDL.Nat, IDL.Vec(AvailabilitySlot)],
        [Result],
        [],
      ),
    'toggleDoctorOnlineStatus' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
    'unpublishBlog' : IDL.Func([IDL.Nat], [Result], []),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateFAQs' : IDL.Func([IDL.Vec(FAQ)], [Result], []),
    'updateHeroSection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'updateServices' : IDL.Func([IDL.Vec(ServiceCard)], [Result], []),
    'updateTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [Result], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };