/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'doctorId' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'slot' : string,
  'updatedAt' : bigint,
  'notes' : string,
  'patientName' : string,
  'phone' : string,
  'problem' : string,
}
export interface AppointmentStats {
  'total' : bigint,
  'completed' : bigint,
  'rejected' : bigint,
  'accepted' : bigint,
}
export interface AppointmentSummary {
  'total' : bigint,
  'cancelled' : bigint,
  'pending' : bigint,
  'completed' : bigint,
  'approved' : bigint,
}
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'userId' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface AvailabilitySlot {
  'endHour' : bigint,
  'dayOfWeek' : string,
  'startHour' : bigint,
}
export interface Blog {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'content' : string,
  'authorId' : string,
  'createdAt' : bigint,
  'blogType' : string,
  'updatedAt' : bigint,
  'imageUrl' : string,
}
export interface ContactInfo {
  'hours' : string,
  'email' : string,
  'address' : string,
  'mapUrl' : string,
  'phone' : string,
}
export interface Doctor {
  'id' : bigint,
  'status' : string,
  'appointmentStats' : AppointmentStats,
  'name' : string,
  'isOnline' : boolean,
  'email' : string,
  'availability' : Array<AvailabilitySlot>,
  'specialization' : string,
  'phone' : string,
  'lastLogin' : bigint,
}
export interface DoctorPublic {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'isOnline' : boolean,
  'email' : string,
  'availability' : Array<AvailabilitySlot>,
  'specialization' : string,
  'phone' : string,
}
export interface FAQ {
  'id' : bigint,
  'question' : string,
  'order' : bigint,
  'answer' : string,
}
export interface Patient {
  'id' : bigint,
  'appointmentIds' : Array<bigint>,
  'name' : string,
  'email' : [] | [string],
  'phone' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export interface ServiceCard {
  'id' : bigint,
  'title' : string,
  'order' : bigint,
  'icon' : string,
  'description' : string,
}
export interface SiteContent {
  'contactInfo' : ContactInfo,
  'faqs' : Array<FAQ>,
  'heroCtaText' : string,
  'heroIntro' : string,
  'testimonials' : Array<Testimonial>,
  'heroTitle' : string,
  'services' : Array<ServiceCard>,
  'heroTagline' : string,
}
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'text' : string,
  'rating' : bigint,
}
export interface TrendEntry { 'date' : string, 'count' : bigint }
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'doctor' : null } |
  { 'staff' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addDoctor' : ActorMethod<[string, string, string, string], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createAppointment' : ActorMethod<
    [string, string, string, string, string, [] | [bigint]],
    Result_1
  >,
  'createBlog' : ActorMethod<[string, string, string, string], Result_1>,
  'deleteAppointment' : ActorMethod<[bigint], Result>,
  'deleteBlog' : ActorMethod<[bigint], Result>,
  'editBlog' : ActorMethod<[bigint, string, string, string, string], Result>,
  'editDoctor' : ActorMethod<[bigint, string, string, string, string], Result>,
  'getAllBlogs' : ActorMethod<[], Array<Blog>>,
  'getAppointmentStats' : ActorMethod<[], AppointmentSummary>,
  'getAppointmentTrend' : ActorMethod<[bigint], Array<TrendEntry>>,
  'getAppointments' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<Appointment>
  >,
  'getAppointmentsByDoctor' : ActorMethod<[bigint], Array<Appointment>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getAuditLogsByUser' : ActorMethod<[string], Array<AuditLog>>,
  'getAvailableSlots' : ActorMethod<[string, [] | [bigint]], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCurrentUser' : ActorMethod<[], [] | [UserProfile]>,
  'getDoctorById' : ActorMethod<[bigint], [] | [Doctor]>,
  'getDoctorStats' : ActorMethod<[bigint], AppointmentStats>,
  'getDoctors' : ActorMethod<[], Array<DoctorPublic>>,
  'getPatientByPhone' : ActorMethod<[string], [] | [Patient]>,
  'getPatientHistory' : ActorMethod<[bigint], Array<Appointment>>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getPublishedBlogs' : ActorMethod<[], Array<Blog>>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishBlog' : ActorMethod<[bigint], Result>,
  'registerUser' : ActorMethod<[Principal, string, string, UserRole], Result>,
  'rescheduleAppointment' : ActorMethod<
    [bigint, string, string, [] | [bigint]],
    Result
  >,
  'saveCallerUserProfile' : ActorMethod<[string, string], Result>,
  'setDoctorAvailability' : ActorMethod<
    [bigint, Array<AvailabilitySlot>],
    Result
  >,
  'toggleDoctorOnlineStatus' : ActorMethod<[bigint, boolean], Result>,
  'unpublishBlog' : ActorMethod<[bigint], Result>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, string, [] | [string]],
    Result
  >,
  'updateContactInfo' : ActorMethod<
    [string, string, string, string, string],
    Result
  >,
  'updateFAQs' : ActorMethod<[Array<FAQ>], Result>,
  'updateHeroSection' : ActorMethod<[string, string, string, string], Result>,
  'updateServices' : ActorMethod<[Array<ServiceCard>], Result>,
  'updateTestimonials' : ActorMethod<[Array<Testimonial>], Result>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];