/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Blog {
    id: bigint;
    status: string;
    title: string;
    content: string;
    authorId: string;
    createdAt: bigint;
    blogType: string;
    updatedAt: bigint;
    imageUrl: string;
}
export interface FAQ {
    id: bigint;
    question: string;
    order: bigint;
    answer: string;
}
export interface AuditLog {
    id: bigint;
    action: string;
    userId: string;
    timestamp: bigint;
    details: string;
}
export interface AppointmentSummary {
    total: bigint;
    cancelled: bigint;
    pending: bigint;
    completed: bigint;
    approved: bigint;
}
export interface AppointmentStats {
    total: bigint;
    completed: bigint;
    rejected: bigint;
    accepted: bigint;
}
export interface TrendEntry {
    date: string;
    count: bigint;
}
export interface AvailabilitySlot {
    endHour: bigint;
    dayOfWeek: string;
    startHour: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Patient {
    id: bigint;
    appointmentIds: Array<bigint>;
    name: string;
    email?: string;
    phone: string;
}
export interface DoctorPublic {
    id: bigint;
    status: string;
    name: string;
    isOnline: boolean;
    email: string;
    availability: Array<AvailabilitySlot>;
    specialization: string;
    phone: string;
}
export interface ServiceCard {
    id: bigint;
    title: string;
    order: bigint;
    icon: string;
    description: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Doctor {
    id: bigint;
    status: string;
    appointmentStats: AppointmentStats;
    name: string;
    isOnline: boolean;
    email: string;
    availability: Array<AvailabilitySlot>;
    specialization: string;
    phone: string;
    lastLogin: bigint;
}
export interface SiteContent {
    contactInfo: ContactInfo;
    faqs: Array<FAQ>;
    heroCtaText: string;
    heroIntro: string;
    testimonials: Array<Testimonial>;
    heroTitle: string;
    services: Array<ServiceCard>;
    heroTagline: string;
}
export interface Appointment {
    id: bigint;
    status: string;
    doctorId: bigint;
    date: string;
    createdAt: bigint;
    slot: string;
    updatedAt: bigint;
    notes: string;
    patientName: string;
    phone: string;
    problem: string;
}
export interface ContactInfo {
    hours: string;
    email: string;
    address: string;
    mapUrl: string;
    phone: string;
}
export interface UserProfile {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
}
export interface Testimonial {
    id: bigint;
    name: string;
    role: string;
    text: string;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    doctor = "doctor",
    staff = "staff"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addDoctor(name: string, specialization: string, email: string, phone: string): Promise<Result_1>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createAppointment(patientName: string, phone: string, problem: string, date: string, slot: string, doctorId: bigint | null): Promise<Result_1>;
    createBlog(title: string, content: string, imageUrl: string, blogType: string): Promise<Result_1>;
    deleteAppointment(id: bigint): Promise<Result>;
    deleteBlog(id: bigint): Promise<Result>;
    editBlog(id: bigint, title: string, content: string, imageUrl: string, blogType: string): Promise<Result>;
    editDoctor(id: bigint, name: string, specialization: string, email: string, phone: string): Promise<Result>;
    getAllBlogs(): Promise<Array<Blog>>;
    getAppointmentStats(): Promise<AppointmentSummary>;
    getAppointmentTrend(days: bigint): Promise<Array<TrendEntry>>;
    getAppointments(statusFilter: string | null, doctorIdFilter: bigint | null): Promise<Array<Appointment>>;
    getAppointmentsByDoctor(doctorId: bigint): Promise<Array<Appointment>>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getAuditLogsByUser(userId: string): Promise<Array<AuditLog>>;
    getAvailableSlots(date: string, doctorId: bigint | null): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCurrentUser(): Promise<UserProfile | null>;
    getDoctorById(id: bigint): Promise<Doctor | null>;
    getDoctorStats(doctorId: bigint): Promise<AppointmentStats>;
    getDoctors(): Promise<Array<DoctorPublic>>;
    getPatientByPhone(phone: string): Promise<Patient | null>;
    getPatientHistory(patientId: bigint): Promise<Array<Appointment>>;
    getPatients(): Promise<Array<Patient>>;
    getPublishedBlogs(): Promise<Array<Blog>>;
    getSiteContent(): Promise<SiteContent>;
    isCallerAdmin(): Promise<boolean>;
    publishBlog(id: bigint): Promise<Result>;
    registerUser(principal: Principal, name: string, email: string, role: UserRole): Promise<Result>;
    rescheduleAppointment(id: bigint, newDate: string, newSlot: string, newDoctorId: bigint | null): Promise<Result>;
    saveCallerUserProfile(name: string, email: string): Promise<Result>;
    setDoctorAvailability(doctorId: bigint, availability: Array<AvailabilitySlot>): Promise<Result>;
    toggleDoctorOnlineStatus(doctorId: bigint, isOnline: boolean): Promise<Result>;
    unpublishBlog(id: bigint): Promise<Result>;
    updateAppointmentStatus(id: bigint, newStatus: string, notes: string | null): Promise<Result>;
    updateContactInfo(address: string, phone: string, email: string, hours: string, mapUrl: string): Promise<Result>;
    updateFAQs(faqs: Array<FAQ>): Promise<Result>;
    updateHeroSection(heroTitle: string, heroTagline: string, heroIntro: string, heroCtaText: string): Promise<Result>;
    updateServices(services: Array<ServiceCard>): Promise<Result>;
    updateTestimonials(testimonials: Array<Testimonial>): Promise<Result>;
    updateUserRole(targetPrincipal: Principal, newRole: UserRole): Promise<Result>;
}
import type { Doctor as _Doctor, Patient as _Patient, Result as _Result, Result_1 as _Result_1, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addDoctor(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint | null): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBlog(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlog(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlog(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAppointment(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBlog(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlog(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlog(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async editBlog(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.editBlog(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editBlog(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async editDoctor(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.editDoctor(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDoctor(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogs(): Promise<Array<Blog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogs();
            return result;
        }
    }
    async getAppointmentStats(): Promise<AppointmentSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentStats();
            return result;
        }
    }
    async getAppointmentTrend(arg0: bigint): Promise<Array<TrendEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentTrend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentTrend(arg0);
            return result;
        }
    }
    async getAppointments(arg0: string | null, arg1: bigint | null): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAppointmentsByDoctor(arg0: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByDoctor(arg0);
            return result;
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getAuditLogsByUser(arg0: string): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogsByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogsByUser(arg0);
            return result;
        }
    }
    async getAvailableSlots(arg0: string, arg1: bigint | null): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorById(arg0: bigint): Promise<Doctor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorById(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorById(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorStats(arg0: bigint): Promise<AppointmentStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorStats(arg0);
            return result;
        }
    }
    async getDoctors(): Promise<Array<DoctorPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getPatientByPhone(arg0: string): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientByPhone(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientByPhone(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientHistory(arg0: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientHistory(arg0);
            return result;
        }
    }
    async getPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatients();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatients();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedBlogs(): Promise<Array<Blog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogs();
            return result;
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishBlog(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlog(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlog(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: Principal, arg1: string, arg2: string, arg3: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async rescheduleAppointment(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleAppointment(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleAppointment(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDoctorAvailability(arg0: bigint, arg1: Array<AvailabilitySlot>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setDoctorAvailability(arg0, arg1);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDoctorAvailability(arg0, arg1);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleDoctorOnlineStatus(arg0: bigint, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDoctorOnlineStatus(arg0, arg1);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDoctorOnlineStatus(arg0, arg1);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishBlog(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishBlog(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishBlog(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: string, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContactInfo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFAQs(arg0: Array<FAQ>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFAQs(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFAQs(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHeroSection(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroSection(arg0, arg1, arg2, arg3);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroSection(arg0, arg1, arg2, arg3);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateServices(arg0: Array<ServiceCard>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServices(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServices(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTestimonials(arg0: Array<Testimonial>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonials(arg0);
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonials(arg0);
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Patient_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Doctor]): Doctor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
}): {
    principal: Principal;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    appointmentIds: Array<bigint>;
    name: string;
    email: [] | [string];
    phone: string;
}): {
    id: bigint;
    appointmentIds: Array<bigint>;
    name: string;
    email?: string;
    phone: string;
} {
    return {
        id: value.id,
        appointmentIds: value.appointmentIds,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.email)),
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    doctor: null;
} | {
    staff: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "doctor" in value ? UserRole.doctor : "staff" in value ? UserRole.staff : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n18(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    doctor: null;
} | {
    staff: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.doctor ? {
        doctor: null
    } : value == UserRole.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
